baseURL = "https://pamelamishra.github.io/"
languageCode = "en-us"
title = "Pamela Mishra"
theme = "FeelIt"

enableRobotsTXT = true

[params]
  defaultTheme = "auto"   # auto | light | dark

[markup]
  [markup.highlight]
    noClasses = false
