baseURL = "https://pamelamishra.github.io/"
languageCode = "en-us"
title = "Pamela Mishra"
theme = "FeelIt"

enableRobotsTXT = true

[params]
  version = "1.0.X"

[markup]
  [markup.highlight]
    noClasses = false
