baseURL = "https://pamelamishra.github.io/"
languageCode = "en-us"
title = "Pamela Mishra"
theme = "PaperMod"

[menu]

  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 10

  [[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 20
